# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
registries:
  yoast:
    type: composer-repository
    url: https://my.yoast.com/packages/
    username: token
    password: ${{secrets.YOAST_SEO_PRO_TOKEN}}
updates:
  - package-ecosystem: "composer"
    directory: "/"
    registries:
      - yoast
    schedule:
      interval: "weekly"
