services:
    fairpm-wordpress:
        networks:
            traefik: ~
            app-net: ~

        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.fairpm.rule=Host(`site.local.fair.pm`)"
            - "traefik.http.routers.fairpm-https.rule=Host(`site.local.fair.pm`)"
            - "traefik.http.routers.fairpm-https.tls=true"

#        volumes:
#            - ./docker/fairpm-wordpress/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini

        ports:
            - "${LOCAL_WEB_PORT:-8080}:80"

    fairpm-db:
        ports:
            - "${LOCAL_DB_PORT:-3306}:3306"
